apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ace-ab-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "X-AB-Test"
    nginx.ingress.kubernetes.io/canary-by-header-value: "B"
spec:
  ingressClassName: nginx
  rules:
    - host: ace-ab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ace-api-b
                port: { number: 80 }
