apiVersion: v1
kind: Service
metadata:
  name: ace-api
spec:
  type: NodePort
  selector:
    app: ace-api
    track: blue   # flip to 'green' to cut traffic over
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
      protocol: TCP
