sonar.projectKey=aceest-fitness
sonar.projectName=ACEest Fitness
sonar.sourceEncoding=UTF-8

# Python layout
sonar.sources=flask/aceest_fitness
sonar.tests=flask/tests
sonar.python.version=3

# Exclude venvs and junk
sonar.exclusions=**/.venv/**,flask/.venv/**

# Reports produced by your pipeline
sonar.python.coverage.reportPaths=flask/coverage.xml
sonar.junit.reportPaths=flask/test-results.xml

# Optional niceties
sonar.test.inclusions=flask/tests/**/*
sonar.cpd.exclusions=flask/tests/**/*
